# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

includes:
  cli:
    taskfile: crates/hanconv-cli/Taskfile.yaml
    dir: crates/hanconv-cli
  app:
    taskfile: crates/hanconv-app/Taskfile.yaml
    dir: crates/hanconv-app

tasks:
  build:
    deps:
      - task: cli:build
      - task: app:build

  dev:
    deps:
      - task: app:dev

  update:
    cmds:
      - cargo update
