# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

includes:
  cli:
    taskfile: crates/hanconv-cli/Taskfile.yaml
    dir: crates/hanconv-cli
  app:
    taskfile: crates/hanconv-app/Taskfile.yaml
    dir: crates/hanconv-app
  tauri:
    taskfile: app/Taskfile.yaml
    dir: app
  web:
    taskfile: web/Taskfile.yaml
    dir: web
  go:
    taskfile: go/Taskfile.yaml
    dir: go
  tools:
    taskfile: tools/Taskfile.yaml
    dir: tools

tasks:
  setup:
    deps:
      - task: web:setup
      - task: app:setup

  build:
    deps:
      - task: go:build
      - task: tools:build
      - task: cli:build
      - task: app:build

  debug:
    deps:
      - task: app:debug

  dev:
    deps:
      - task: app:dev

  update-dictionaries:
    dir: tools
    cmd: go run ./update ../crates/hanconv/data ../go/dict/data

  update:
    deps:
      - task: tools:update
      - task: go:update
      - task: web:update
    cmds:
      - task: update-dictionaries
      - cargo update
