version: 3

tasks:
  dev:
    cmd: cargo run

  run:
    cmd: cargo run --release

  build:
    cmd: cargo build --release

  package:
    cmd: cargo package

  publish:
    cmd: cargo publish

  install:
    cmd: cargo install --path .
