set shell := ["nu", "-c"]
set script-interpreter := ["nu"]
set indentation := "  "
set default-list := true
set fallback

run *args:
  cargo run {{args}}

build:
  cargo build --release

package:
  cargo package

publish:
  cargo publish

install:
  cargo install --path .
