# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

tasks:
  build-windows:
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build -o ./bin/ ./cmd/...

  build:
    deps:
      - build-windows

  install:
    cmds:
      - go install ./cmd/hanconv

  update:
    cmd: go get -u all
