[package]
name = "hanconv-wasm"
version = "0.3.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
hanconv = { workspace = true }
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
