name: Release

on:
  push:
    tags: [ "v*.*.*" ]

defaults:
  run:
    shell: nu {0}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Set up Nushell
        uses: hustcer/setup-nu@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          rustflags: ""

      - name: Set up Task
        run: |
          winget install --id Task.Task --accept-source-agreements --accept-package-agreements
          $env.LOCALAPPDATA | path join Microsoft WinGet Links | save -a $env:GITHUB_PATH

      - name: Build
        run: |
          task cli:build
          task app:build

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            target/release/hanconv.exe
            target/release/hanconv-app.exe
